### ISSUE TITLE
Extensive real world test suite passes

### ISSUE THREAD

**Issue by roll** [okfn/datapackage-storage-py#1]
Datapackage sources:
- https://github.com/datasets
- https://github.com/os-data
- https://github.com/openspending/fiscal-data-package-demos

SQL:
- [ ] country-codes (required field issue - https://github.com/okfn/jsontableschema-py/pull/45)
- [x] country-list
- [ ] currency-codes (not valid datapackage - https://github.com/datasets/currency-codes/pull/6, https://github.com/datasets/currency-codes/issues/2)
- [ ] finance-vix (type support - https://github.com/okfn/jsontableschema-sql-py/issues/9)
- [x] gb-country-regional-analysis (reduced, minor tweaks)
- [ ] gb-country-regional-analysis (not valid datapackage)
- [ ] gdp (type support - https://github.com/okfn/jsontableschema-sql-py/issues/9)
- [ ] imf-weo (required field issue - https://github.com/okfn/jsontableschema-py/pull/45)
- [ ] language-codes (required field issue - https://github.com/okfn/jsontableschema-py/pull/45)
- [x] nasdaq-listings
- [ ] population (invalid data package - https://github.com/datasets/population/pull/2)
- [ ] registry (required field issue - https://github.com/okfn/jsontableschema-py/pull/45)
- [ ] s-and-p-500 (invalid data package - https://github.com/datasets/s-and-p-500/pull/3)
- [ ] s-and-p-500-companies (required field issue - https://github.com/okfn/jsontableschema-py/pull/45)
- [x] testing
- [ ] un-locode (required field issue - https://github.com/okfn/jsontableschema-py/pull/45, slow because of validation)

BigQuery:
- [ ] country-codes (required field issue - https://github.com/okfn/jsontableschema-py/pull/45)
- [ ] country-list (python3 encoding problem - https://github.com/okfn/jsontableschema-bigquery-py/issues/13)
- [ ] currency-codes (not valid datapackage - https://github.com/datasets/currency-codes/pull/6, https://github.com/datasets/currency-codes/issues/2)
- [ ] finance-vix (type support - https://github.com/okfn/jsontableschema-bigquery-py/issues/1)
- [x] gb-country-regional-analysis (reduced, minor tweaks)
- [ ] gb-country-regional-analysis (not valid datapackage)
- [ ] gdp (type support - https://github.com/okfn/jsontableschema-bigquery-py/issues/1)
- [ ] imf-weo (required field issue - https://github.com/okfn/jsontableschema-py/pull/45)
- [ ] language-codes (required field issue - https://github.com/okfn/jsontableschema-py/pull/45)
- [x] nasdaq-listings
- [ ] population (invalid data package - https://github.com/datasets/population/pull/2)
- [ ] registry (required field issue - https://github.com/okfn/jsontableschema-py/pull/45)
- [ ] s-and-p-500 (invalid data package - https://github.com/datasets/s-and-p-500/pull/3)
- [ ] s-and-p-500-companies (required field issue - https://github.com/okfn/jsontableschema-py/pull/45)
- [x] testing
- [ ] un-locode (required field issue - https://github.com/okfn/jsontableschema-py/pull/45)

**Comment by roll** [comment]
See - https://github.com/frictionlessdata/testsuite-py
